version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./metabase/config/mongo.env

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongodb

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    env_file:
      - ./metabase/config/postgres.env
    ports:
      - "5432:5432"
    networks:
      - metanet1

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    restart: always
    env_file:
      - ./metabase/config/metabase_database.env
    depends_on:
      - postgres
    networks:
      - metanet1
    ports:
      - 3000:3000

networks:
  metanet1:
    driver: bridge
