name: Github CI
on:
  # Configura servidor de CI para executar o pipeline de tarefas abaixo (jobs) quando
  # um push ou pull request for realizado tendo como alvo a branch main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest # Os comandos serão executados em um sistema operacional Linux

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 # Faz o checkout do código recebido

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      # - name: Set up JDK 1.8
      #   uses: actions/setup-java@v1 # Configura o Java 1.8
      #   with:
      #     java-version: 1.8

      # - name: Build
      #   run: mvn package -Dmaven.test.skip=true # Compila o código fonte

      # - name: Unit Test
      #   run: mvn test # Executada os testes de unidade

      - name: "Test server"
        run: |
        docker exec -it app-1 pip install pytest
        docker exec -it app-1 pytest tests

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
